### ISSUE TITLE
A version without OES_texture_float

### ISSUE THREAD

**Issue by gunta** [stormcolor/webclgl#1]
Hi! 
I would like to see an option to turn off OES_texture_float.

The new iOS 8 which supports WebGL doesn't have that extension, but despite everything, it will make for some interesting use cases.

I'm thinking of doing something like suggested here:
http://stackoverflow.com/a/12061257
(encoding floats as bytes).

Thank you!

**Comment by gunta** [comment]
Any update on this?

**Comment by 3DRoberto** [comment]
Hi Gunta.
In my case I do not have yet a Iphone with which to carry out tests, whereby could not indicate about it.
