### ISSUE TITLE
Float encoding

### ISSUE THREAD

**Issue by redhog** [stormcolor/webclgl#14]
Hi!

I found this library after trying to build something similar myself. However, this library has a limitation in how float values are read from the shader to javascript (using readPixels): Values are encoded as val=r + g/255 + b/255^2 + a/255^3. This means that all valid float32 values can not be encoded, even though you are using 32bits of data. Worse, you have to unpack this encoding in javascript, meaning that for simpler operations, your paralellization doesn't actually lead to any speed gains.

Below is my glsl code to encode a float value into RGBA in proper IEEE float32 format that can be read directly in the output buffer without per-value javascript processing.

Here is the javascript to read the values:

        var pixels = new Uint8Array(4 * width * height);
        self.gl.readPixels(x || 0, y || 0, width, height, self.gl.RGBA, self.gl.UNSIGNED_BYTE, pixels);
        return new Float32Array(pixels.buffer);

And here is the glsl code:

      numjs.shaders.float2color = function() {
        var handleLittleEndian = '';
        if (numjs.isLittleEndian()) {
          handleLittleEndian = `
            res = vec4(res[3], res[2], res[1], res[0]);
          `;
        }
        return `
          bool isnan(float val) {
            return (val < 0.0 || 0.0 < val || val == 0.0) ? false : true;
          }
          bool isinf(float val) {
            return (val != 0.0 && val * 2.0 == val) ? true : false;
          }
          vec4 float2color(float value) {
            float sign = 0.0;
            float exp = 0.0;
            vec3 frac = vec3(0.0, 0.0, 0.0);
            if (value < 0.0) {
              sign = 1.0;
              value = -value;
            }
            if (isnan(value)) {
              exp = 255.0;
              frac = vec3(64.0, 0.0, 0.0);
            } else if (isinf(value)) {
              exp = 255.0;
              frac = vec3(0.0, 0.0, 0.0);
            } else if (value == 0.0) {
              exp = 0.0;
              frac = vec3(0.0, 0.0, 0.0);
            } else {
              exp = floor(log2(value)) + 127.0;
              // while (value < exp2(23.0)) {
              for (int i = 0; i < 24; i++) {
                if (value >= exp2(23.0)) break;
                value = value * 2.0;
              }
              value = value - exp2(23.0);
              frac[0] = floor(value / exp2(16.0));
              value = value - frac[0] * exp2(16.0);
              frac[1] = floor(value / exp2(8.0));
              value = value - frac[1] * exp2(8.0);
              frac[2] = value;
            }
            vec4 res = vec4(
              sign * 128.0 + floor(exp / 2.0),
              mod(exp, 2.0) * 128.0 + frac[0],
              frac[1],
              frac[2]
            ) / vec4(255.0, 255.0, 255.0, 255.0);

            if (isLittleEndian) {
              res = vec4(res[3], res[2], res[1], res[0]);
            }

            return res;
          }

Source code of the whole experimentation (including code for detecting little-/big-endianness):
https://github.com/redhog/numjs/blob/master/test.html#L152

**Comment by redhog** [comment]
@3DRoberto Heyas! Did this code / comment help you? I see your code has changed quite a bit so maybe it's not relevant any more and that''s why you just closed it? Just being curious...

**Comment by 3DRoberto** [comment]
Hi @redhog ,
yes the code has changed a little. I hope you can make things without problems if you use.
Regards
