### ISSUE TITLE
it's doesn't work in ios & android :(

### ISSUE THREAD

**Issue by cnwander** [stormcolor/webclgl#15]
it's OK in desktop browers, but cann't work in mobile browsers
`var result = gpufor({"float4* A": pixels.slice(0, 512*512)}, "n", "FLOAT4",
    "float r = A[n].x;"+
    "float g = A[n].y;"+
    "float b = A[n].z;"+
    "float _max = max(max(r, g), b);"+
    "float _min = min(min(r, g), b);"+
    "float d = _max - _min;"+
    "float h;"+
    "float s = _max == 0.0 ? 0.0 : d / _max;"+
    "float v = _max / 255.0;" +
    "if(_max == _min){ h = 0.0;}"+
    "else if(_max == r){ h = (g - b) + d * (g < b ? 6.0: 0.0); h /= 6.0 * d;}"+
    "else if(_max == g){ h = (b - r) + d * 2.0; h /= 6.0 * d;}"+
    "else if(_max == b){ h = (r - g) + d * 4.0; h /= 6.0 * d;}"+
    "vec4 a = vec4(h, s, v, 1.0);"+
    "return a;");`

**Comment by cnwander** [comment]
thank you all the same

**Comment by 3DRoberto** [comment]
Now exists libraries like gpu.js that implement this algorithm and it have more people contributing.
Regards @cnwander ;)

**Comment by 3DRoberto** [comment]
Now working @cnwander ;)
