### ISSUE TITLE
implement sha256 hash

### ISSUE THREAD

**Issue by Morgiver** [stormcolor/webclgl#16]
Hi, i'm doing some research to calculate SHA256 hashes with my graphic card in my browser.
I was wondering, in case of use Webclgl, if i have to rewrite a complete SHA256 method in Webclgl or if i can use a lib like Web Crypto Api directly in Webclgl ?

**Comment by 3DRoberto** [comment]
Hi @Morgiver,
Still I don't know very much respect the algorithm but I think that you should implement this method yourself and the Web Crypto Api (which also I don't knew) not help much.

**Comment by 3DRoberto** [comment]
Really it would be interesting implement this. 
Regards ;)
