### ISSUE TITLE
simpler  benchmark expression "A/(A+B)" leading to poorer performance for GPU

### ISSUE THREAD

**Issue by oscaralvaro** [stormcolor/webclgl#6]
I modified the code to perform a simpler operation "A/(A+B)" and now I see the GPU taking four times. What am I doing wrong?

Any ideas why this happens?

**Comment by oscaralvaro** [comment]
Here is the modified benchmark 
https://rawgit.com/oscaralvaro/webclgl/master/demos/benchmarks/index.html

**Comment by 3DRoberto** [comment]
The greatest benefit is obtained when the calculation is more extensive.
If the operation is not very complex, WebCLGL may take longer during internal unpacking and other actions.
