### ISSUE TITLE
webgl 2 support

### ISSUE THREAD

**Issue by acterhd** [stormcolor/webclgl#9]
webclgl support webgl2 or not?

**Comment by 3DRoberto** [comment]
Hi acterhd. I updated to allow WebGL2 context.

Regards ;)

**Comment by acterhd** [comment]
have you multiple render target support?

**Comment by 3DRoberto** [comment]
At this moment any WebGL2 advantage is included in WebCLGL but these will be incorporated progressively.

**Comment by 3DRoberto** [comment]
I just made some improvements and I think I will try to integrate multi-render-target. Thank you very much for your advice, I had not known that this capacity is available now as extension in WebGL ;)

**Comment by 3DRoberto** [comment]
Hi acterhd, now it´s possible to save in multiple variables in the kernel result ;)
